
name: Bump Version
on:
  pull_request:
    branches:
      - dev
    paths-ignore:
      - 'version.py'

jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{github.event.pull_request.head.repo.full_name}}
          ref: ${{GITHUB.HEAD_REF}}
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Increment Version
        run: |
          VER=$(python setup.py --version)
          python version_bump.py
      - name: Push Version Change
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Increment Version