# This workflow will run unit tests

name: Test Utilities
on:
  push:
  workflow_dispatch:

# TODO: Run tests here for everything in NeonCore
jobs:
  util_tests:
    strategy:
      matrix:
        python-version: [ 3.6, 3.7, 3.8 ]
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          sudo apt install -y gcc libfann-dev swig libssl-dev portaudio19-dev git
          pip install -r requirements/requirements.txt
          pip install -r requirements/test.txt
        env:
          GITHUB_TOKEN: ${{secrets.neon_token}}
      - name: Test Skill Utils
        run: |
          pytest test/test_skill_utils.py
        env:
          GITHUB_TOKEN: ${{secrets.neon_token}}