name: Propose Stable Release
on:
  workflow_dispatch:
jobs:
  update_version:
    uses: neongeckocom/.github/.github/workflows/propose_dated_release.yml@master
  pull_changes:
    uses: neongeckocom/.github/.github/workflows/pull_master.yml@master
    with:
      pr_reviewer: neonreviewers
      pr_assignee: ${{ github.actor }}
