# This workflow will generate a PR for changes in cert into master

name: Pull to Master
on:
  push:
    branches:
      - dev

jobs:
  pull_changes:
    uses: neongeckocom/.github/.github/workflows/pull_master.yml@master
    with:
      pr_reviewer: neonreviewers
      pr_assignee: neondaniel
